version: '3.9'

services:

  # ── Bases de datos ──────────────────────────────────────────

  user-db:
    image: postgres:16-alpine
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
    ports:
      - "5433:5432"    # Puerto externo diferente para cada BD
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-db:
    image: postgres:16-alpine
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_admin
      POSTGRES_PASSWORD: product_password
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_admin -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:16-alpine
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_admin
      POSTGRES_PASSWORD: order_password
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_admin -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Message Broker ──────────────────────────────────────────

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: marketplace_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"    # Puerto AMQP (para la app)
      - "15672:15672"  # Puerto de la UI de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_db_data:
  product_db_data:
  order_db_data:
  rabbitmq_data: